services:
  mc:
    image: itzg/minecraft-server:latest
    pull_policy: daily
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      TYPE: "NEOFORGE"
      VERSION: "1.21.1"
      DIFFICULTY: "hard"
      PACKWIZ-URL: "https://raw.githubusercontent.com/marceloalckmin/craftops/feat/server-base/pack/pack.toml" #IMPORTANT!!!!!!! CHANGE THIS TO MAIN AFTER MERGE



    volumes:
      - ./minecraft-data:/data
      - ./mods:/mods