name = "R8US Pack"
author = "Samanta"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f0afb05eb0eeef81f778446cf2a1fd90dcf5f147678ff1e66375179e947dbe0f"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.255"
