name = "R8US Pack"
author = "Samanta"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b48aa6b60923e8700d259fbbbea8810530ec601a24f6edda8faec93ef980d29a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.255"
