name = "R8US Pack"
author = "Samanta"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3c93b61777a5ca18cc1b2cb8d06807e5c6a6bfc47a5fd37033395d6ab5d687a6"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.255"
